/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Eider
 */

import org.jdesktop.swingx.JXDatePicker;

public class addChangeSchedule extends javax.swing.JFrame {

    /**
     * Creates new form addCompetition
     */
    public addChangeSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_discipline = new javax.swing.JLabel();
        jLabel_competition = new javax.swing.JLabel();
        jLabel_round = new javax.swing.JLabel();
        jLabel_date = new javax.swing.JLabel();
        jLabel_gender = new javax.swing.JLabel();
        jPanel_header = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_viewTitle = new javax.swing.JLabel();
        jLabel_hyphen = new javax.swing.JLabel();
        jLabel_schCode = new javax.swing.JLabel();
        jButton_save = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jComboBox_competition = new javax.swing.JComboBox<>();
        jComboBox_discipline = new javax.swing.JComboBox<>();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jComboBox_round = new javax.swing.JComboBox<>();
        jXDatePicker_schDate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_discipline.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_discipline.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_discipline.setText("DISCIPLINE:");
        jPanel1.add(jLabel_discipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel_competition.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_competition.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_competition.setText("COMPETITION:");
        jPanel1.add(jLabel_competition, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel_round.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_round.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_round.setText("ROUND:");
        jPanel1.add(jLabel_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel_date.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_date.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_date.setText("DATE:");
        jPanel1.add(jLabel_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        jLabel_gender.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_gender.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_gender.setText("GENDER:");
        jPanel1.add(jLabel_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jPanel_header.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_exit4.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, 50));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_minimize_1.png"))); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 50, 50));

        jLabel_viewTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_viewTitle.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_viewTitle.setText("SCHEDULE");
        jPanel_header.add(jLabel_viewTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 30));

        jLabel_hyphen.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_hyphen.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_hyphen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_hyphen.setText("-");
        jPanel_header.add(jLabel_hyphen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 30));

        jLabel_schCode.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_schCode.setForeground(new java.awt.Color(210, 87, 34));
        jPanel_header.add(jLabel_schCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 30));

        jPanel1.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 50));

        jButton_save.setBackground(new java.awt.Color(163, 67, 26));
        jButton_save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(52, 50, 46));
        jButton_save.setText("SAVE");
        jButton_save.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 140, 50));

        jButton_reset.setBackground(new java.awt.Color(163, 67, 26));
        jButton_reset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(52, 50, 46));
        jButton_reset.setText("RESET");
        jButton_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 140, 50));

        jComboBox_competition.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_competition.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jComboBox_competition, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 300, 30));

        jComboBox_discipline.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_discipline.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jComboBox_discipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 300, 30));

        jComboBox_gender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_gender.setForeground(new java.awt.Color(52, 50, 46));
        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(jComboBox_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 300, 30));

        jComboBox_round.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_round.setForeground(new java.awt.Color(52, 50, 46));
        jComboBox_round.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Round", "Second Round", "Semi Finals", "Finals" }));
        jComboBox_round.setToolTipText("");
        jPanel1.add(jComboBox_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 300, 30));

        jXDatePicker_schDate.setForeground(new java.awt.Color(52, 50, 46));
        jXDatePicker_schDate.setToolTipText("Schedule Date");
        jXDatePicker_schDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jXDatePicker_schDate.setName(""); // NOI18N
        jPanel1.add(jXDatePicker_schDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    int xMouse;
    int yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_reset;
    public javax.swing.JButton jButton_save;
    public javax.swing.JComboBox<String> jComboBox_competition;
    public javax.swing.JComboBox<String> jComboBox_discipline;
    public javax.swing.JComboBox<String> jComboBox_gender;
    public javax.swing.JComboBox<String> jComboBox_round;
    private javax.swing.JLabel jLabel_competition;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_discipline;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_gender;
    public javax.swing.JLabel jLabel_hyphen;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_round;
    public javax.swing.JLabel jLabel_schCode;
    private javax.swing.JLabel jLabel_viewTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_header;
    public org.jdesktop.swingx.JXDatePicker jXDatePicker_schDate;
    // End of variables declaration//GEN-END:variables
}
