/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author Eider
 */
public class addChangeResult extends javax.swing.JFrame {

    /**
     * Creates new form addCompetition
     */
    public addChangeResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_addAthlete = new javax.swing.JPanel();
        jLabel_discipline = new javax.swing.JLabel();
        jLabel_competition = new javax.swing.JLabel();
        jLabel_athlete = new javax.swing.JLabel();
        jLabel_gender = new javax.swing.JLabel();
        jPanel_header = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_viewTitle = new javax.swing.JLabel();
        jLabel_hyphen = new javax.swing.JLabel();
        jLabel_rsCode = new javax.swing.JLabel();
        jButton_save = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jLabel_time = new javax.swing.JLabel();
        jTextField_time = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel_rsDate = new javax.swing.JLabel();
        jLabel_position = new javax.swing.JLabel();
        jTextField_position = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel_round = new javax.swing.JLabel();
        jXDatePicker_rsDate = new org.jdesktop.swingx.JXDatePicker();
        jComboBox_athlete = new javax.swing.JComboBox<>();
        jComboBox_round = new javax.swing.JComboBox<>();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jComboBox_competition = new javax.swing.JComboBox<>();
        jComboBox_discipline = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel_addAthlete.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_addAthlete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel_addAthlete.setPreferredSize(new java.awt.Dimension(1298, 782));
        jPanel_addAthlete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_discipline.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_discipline.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_discipline.setText("DISCIPLINE:");
        jPanel_addAthlete.add(jLabel_discipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel_competition.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_competition.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_competition.setText("COMPETITION:");
        jPanel_addAthlete.add(jLabel_competition, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel_athlete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_athlete.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_athlete.setText("ATHLETE:");
        jPanel_addAthlete.add(jLabel_athlete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel_gender.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_gender.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_gender.setText("GENDER:");
        jPanel_addAthlete.add(jLabel_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 20));

        jPanel_header.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_exit4.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 50, 50));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_minimize_1.png"))); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 50, 50));

        jLabel_viewTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_viewTitle.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_viewTitle.setText("RESULT");
        jPanel_header.add(jLabel_viewTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, 30));

        jLabel_hyphen.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_hyphen.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_hyphen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_hyphen.setText("-");
        jPanel_header.add(jLabel_hyphen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 30, 30));

        jLabel_rsCode.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_rsCode.setForeground(new java.awt.Color(210, 87, 34));
        jPanel_header.add(jLabel_rsCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 30));

        jPanel_addAthlete.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 50));

        jButton_save.setBackground(new java.awt.Color(163, 67, 26));
        jButton_save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(52, 50, 46));
        jButton_save.setText("SAVE");
        jButton_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_addAthlete.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 140, 50));

        jButton_reset.setBackground(new java.awt.Color(163, 67, 26));
        jButton_reset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(52, 50, 46));
        jButton_reset.setText("RESET");
        jButton_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });
        jPanel_addAthlete.add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 140, 50));

        jLabel_time.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_time.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_time.setText("TIME:");
        jPanel_addAthlete.add(jLabel_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jTextField_time.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_time.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_time.setText("Enter the time");
        jTextField_time.setBorder(null);
        jTextField_time.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_timeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_timeFocusLost(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 300, 30));

        jSeparator10.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator10.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 300, 10));

        jLabel_rsDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_rsDate.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_rsDate.setText("DATE:");
        jPanel_addAthlete.add(jLabel_rsDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, 20));

        jLabel_position.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_position.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_position.setText("POSITION:");
        jPanel_addAthlete.add(jLabel_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jTextField_position.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_position.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_position.setText("Enter the position");
        jTextField_position.setBorder(null);
        jTextField_position.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_positionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_positionFocusLost(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 300, 30));

        jSeparator14.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator14.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 300, 10));

        jLabel_round.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_round.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_round.setText("ROUND:");
        jPanel_addAthlete.add(jLabel_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));
        jPanel_addAthlete.add(jXDatePicker_rsDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 300, 30));

        jComboBox_athlete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_athlete.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jComboBox_athlete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 300, 30));

        jComboBox_round.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_round.setForeground(new java.awt.Color(52, 50, 46));
        jComboBox_round.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Round", "Second Round", "Semi Finals", "Final" }));
        jComboBox_round.setToolTipText("");
        jPanel_addAthlete.add(jComboBox_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 300, 30));

        jComboBox_gender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_gender.setForeground(new java.awt.Color(52, 50, 46));
        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel_addAthlete.add(jComboBox_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 300, 30));

        jComboBox_competition.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_competition.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jComboBox_competition, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 300, 30));

        jComboBox_discipline.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox_discipline.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jComboBox_discipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_addAthlete, javax.swing.GroupLayout.PREFERRED_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_addAthlete, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jTextField_timeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_timeFocusGained
        if(jTextField_time.getText().equals("Enter the time"))
        {
            jTextField_time.setText("");
            jTextField_time.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_timeFocusGained

    private void jTextField_timeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_timeFocusLost
        if(jTextField_time.getText().equals(""))
        {
            jTextField_time.setText("Enter the time");
        }
    }//GEN-LAST:event_jTextField_timeFocusLost

    private void jTextField_positionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_positionFocusGained
        if(jTextField_position.getText().equals("Enter the position"))
        {
            jTextField_position.setText("");
            jTextField_position.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_positionFocusGained

    private void jTextField_positionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_positionFocusLost
        if(jTextField_position.getText().equals(""))
        {
            jTextField_position.setText("Enter the position");
        }
    }//GEN-LAST:event_jTextField_positionFocusLost

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        jTextField_position.setText("Enter the position");
        jTextField_time.setText("Enter the time");
        jComboBox_athlete.setSelectedIndex(0);
        jComboBox_competition.setSelectedIndex(0);
        jComboBox_discipline.setSelectedIndex(0);
        jComboBox_round.setSelectedIndex(0);
        jComboBox_gender.setSelectedIndex(0);
        jXDatePicker_rsDate.setDate(null);
    }//GEN-LAST:event_jButton_resetActionPerformed

    int xMouse;
    int yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_reset;
    public javax.swing.JButton jButton_save;
    public javax.swing.JComboBox<String> jComboBox_athlete;
    public javax.swing.JComboBox<String> jComboBox_competition;
    public javax.swing.JComboBox<String> jComboBox_discipline;
    public javax.swing.JComboBox<String> jComboBox_gender;
    public javax.swing.JComboBox<String> jComboBox_round;
    private javax.swing.JLabel jLabel_athlete;
    private javax.swing.JLabel jLabel_competition;
    private javax.swing.JLabel jLabel_discipline;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_gender;
    public javax.swing.JLabel jLabel_hyphen;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_position;
    private javax.swing.JLabel jLabel_round;
    public javax.swing.JLabel jLabel_rsCode;
    private javax.swing.JLabel jLabel_rsDate;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JLabel jLabel_viewTitle;
    private javax.swing.JPanel jPanel_addAthlete;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator14;
    public javax.swing.JTextField jTextField_position;
    public javax.swing.JTextField jTextField_time;
    public org.jdesktop.swingx.JXDatePicker jXDatePicker_rsDate;
    // End of variables declaration//GEN-END:variables
}
