/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Eider
 */
public class addChangeCompetition extends javax.swing.JFrame {

    /**
     * Creates new form addCompetition
     */
    public addChangeCompetition() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_description = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel_name = new javax.swing.JLabel();
        jTextField_location = new javax.swing.JTextField();
        jLabel_startDate = new javax.swing.JLabel();
        jLabel_location = new javax.swing.JLabel();
        jTextField_description = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel_endDate = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jPanel_header = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_viewTitle = new javax.swing.JLabel();
        jButton_save = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jXDatePicker_endDate = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker_startDate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator4.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 300, 10));

        jLabel_description.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_description.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_description.setText("DESCRIPTION:");
        jPanel1.add(jLabel_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator5.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 300, 10));

        jLabel_name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_name.setText("NAME:");
        jPanel1.add(jLabel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jTextField_location.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_location.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_location.setText("Enter the location");
        jTextField_location.setBorder(null);
        jTextField_location.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_locationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_locationFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 300, 30));

        jLabel_startDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_startDate.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_startDate.setText("START DATE:");
        jPanel1.add(jLabel_startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel_location.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_location.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_location.setText("LOCATION:");
        jPanel1.add(jLabel_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        jTextField_description.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_description.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_description.setText("Enter the description");
        jTextField_description.setBorder(null);
        jTextField_description.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_descriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_descriptionFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 300, 30));

        jSeparator6.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator6.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 300, 10));

        jLabel_endDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_endDate.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_endDate.setText("END DATE:");
        jPanel1.add(jLabel_endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jTextField_name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_name.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_name.setText("Enter the name");
        jTextField_name.setBorder(null);
        jTextField_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 300, 30));

        jPanel_header.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_exit4.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, 50));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_minimize_1.png"))); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 50, 50));

        jLabel_viewTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_viewTitle.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_viewTitle.setText("COMPETITION");
        jPanel_header.add(jLabel_viewTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 280, 30));

        jPanel1.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 50));

        jButton_save.setBackground(new java.awt.Color(163, 67, 26));
        jButton_save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(52, 50, 46));
        jButton_save.setText("SAVE");
        jButton_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 140, 50));

        jButton_reset.setBackground(new java.awt.Color(163, 67, 26));
        jButton_reset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(52, 50, 46));
        jButton_reset.setText("RESET");
        jButton_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 140, 50));

        jXDatePicker_endDate.setForeground(new java.awt.Color(52, 50, 46));
        jXDatePicker_endDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jXDatePicker_endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 300, 30));

        jXDatePicker_startDate.setForeground(new java.awt.Color(52, 50, 46));
        jXDatePicker_startDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jXDatePicker_startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_descriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_descriptionFocusGained
        if(jTextField_description.getText().equals("Enter the description"))
        {
            jTextField_description.setText("");
        }
    }//GEN-LAST:event_jTextField_descriptionFocusGained

    private void jTextField_descriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_descriptionFocusLost
        if(jTextField_description.getText().equals(""))
        {
            jTextField_description.setText("Enter the description");
        }
    }//GEN-LAST:event_jTextField_descriptionFocusLost

    private void jTextField_locationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_locationFocusGained
        if(jTextField_location.getText().equals("Enter the location"))
        {
            jTextField_location.setText("");
        }
    }//GEN-LAST:event_jTextField_locationFocusGained

    private void jTextField_locationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_locationFocusLost
        if(jTextField_location.getText().equals(""))
        {
            jTextField_location.setText("Enter the location");
        }
    }//GEN-LAST:event_jTextField_locationFocusLost

    private void jTextField_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusGained
        if(jTextField_name.getText().equals("Enter the name"))
        {
            jTextField_name.setText("");
        }
    }//GEN-LAST:event_jTextField_nameFocusGained

    private void jTextField_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusLost
        if(jTextField_name.getText().equals(""))
        {
            jTextField_name.setText("Enter the name");
        }
    }//GEN-LAST:event_jTextField_nameFocusLost

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    int xMouse;
    int yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_reset;
    public javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel_description;
    private javax.swing.JLabel jLabel_endDate;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_location;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_startDate;
    private javax.swing.JLabel jLabel_viewTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField jTextField_description;
    public javax.swing.JTextField jTextField_location;
    public javax.swing.JTextField jTextField_name;
    public org.jdesktop.swingx.JXDatePicker jXDatePicker_endDate;
    public org.jdesktop.swingx.JXDatePicker jXDatePicker_startDate;
    // End of variables declaration//GEN-END:variables
}
