/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Eider
 */
public class addChangeAthlete extends javax.swing.JFrame {

    /**
     * Creates new form addCompetition
     */
    public addChangeAthlete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_addAthlete = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField_phoneNum = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_country = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel_id = new javax.swing.JLabel();
        jTextField_nationality = new javax.swing.JTextField();
        jLabel_phoneNum = new javax.swing.JLabel();
        jLabel_nationality = new javax.swing.JLabel();
        jTextField_country = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel_seasonBest = new javax.swing.JLabel();
        jTextField_seasonBest = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTextField_id = new javax.swing.JTextField();
        jPanel_header = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_viewTitle = new javax.swing.JLabel();
        jButton_save = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jLabel_name = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel_surname = new javax.swing.JLabel();
        jTextField_surname = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel_homeTown = new javax.swing.JLabel();
        jTextField_homeTown = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel_address = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel_birthDate = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel_favDiscipline = new javax.swing.JLabel();
        jTextField_favDiscipline = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel_personalBest = new javax.swing.JLabel();
        jTextField_personalBest = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel_numMedals = new javax.swing.JLabel();
        jTextField_numMedals = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel_team = new javax.swing.JLabel();
        jXDatePicker_birthDate = new org.jdesktop.swingx.JXDatePicker();
        jComboBox_team = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel_addAthlete.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_addAthlete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel_addAthlete.setPreferredSize(new java.awt.Dimension(1298, 782));
        jPanel_addAthlete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator4.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 300, 10));

        jTextField_phoneNum.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_phoneNum.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_phoneNum.setText("Enter the phone number");
        jTextField_phoneNum.setBorder(null);
        jTextField_phoneNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_phoneNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_phoneNumFocusLost(evt);
            }
        });
        jTextField_phoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phoneNumKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_phoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 300, 30));

        jSeparator3.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator3.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 300, 10));

        jLabel_country.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_country.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_country.setText("COUNTRY:");
        jPanel_addAthlete.add(jLabel_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator5.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 300, 10));

        jLabel_id.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_id.setText("ID:");
        jPanel_addAthlete.add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jTextField_nationality.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_nationality.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_nationality.setText("Enter the nationality");
        jTextField_nationality.setBorder(null);
        jTextField_nationality.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nationalityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nationalityFocusLost(evt);
            }
        });
        jTextField_nationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nationalityKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 300, 30));

        jLabel_phoneNum.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_phoneNum.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_phoneNum.setText("PHONE NUMBER:");
        jPanel_addAthlete.add(jLabel_phoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel_nationality.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_nationality.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_nationality.setText("NATIONALITY:");
        jPanel_addAthlete.add(jLabel_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        jTextField_country.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_country.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_country.setText("Enter the country");
        jTextField_country.setBorder(null);
        jTextField_country.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_countryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_countryFocusLost(evt);
            }
        });
        jTextField_country.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_countryKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 300, 30));

        jSeparator6.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator6.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 300, 10));

        jLabel_seasonBest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_seasonBest.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_seasonBest.setText("SEASON BEST:");
        jPanel_addAthlete.add(jLabel_seasonBest, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jTextField_seasonBest.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_seasonBest.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_seasonBest.setText("Enter the season best");
        jTextField_seasonBest.setBorder(null);
        jTextField_seasonBest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_seasonBestFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_seasonBestFocusLost(evt);
            }
        });
        jTextField_seasonBest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_seasonBestKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_seasonBest, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 300, 30));

        jSeparator7.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator7.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 300, 10));

        jTextField_id.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_id.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_id.setText("e.g. 78451256M");
        jTextField_id.setBorder(null);
        jTextField_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_idFocusLost(evt);
            }
        });
        jTextField_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 300, 30));

        jPanel_header.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_exit4.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 50, 50));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_minimize_1.png"))); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 50, 50));

        jLabel_viewTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_viewTitle.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_viewTitle.setText("ATHLETE");
        jPanel_header.add(jLabel_viewTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 280, 30));

        jPanel_addAthlete.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 50));

        jButton_save.setBackground(new java.awt.Color(163, 67, 26));
        jButton_save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(52, 50, 46));
        jButton_save.setText("SAVE");
        jButton_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_addAthlete.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 140, 50));

        jButton_reset.setBackground(new java.awt.Color(163, 67, 26));
        jButton_reset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(52, 50, 46));
        jButton_reset.setText("RESET");
        jButton_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });
        jPanel_addAthlete.add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 140, 50));

        jLabel_name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_name.setText("NAME:");
        jPanel_addAthlete.add(jLabel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jTextField_name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_name.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_name.setText("Enter the name");
        jTextField_name.setBorder(null);
        jTextField_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusLost(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 300, 30));

        jSeparator8.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator8.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 300, 10));

        jLabel_surname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_surname.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_surname.setText("SURNAME:");
        jPanel_addAthlete.add(jLabel_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, -1, -1));

        jTextField_surname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_surname.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_surname.setText("Enter the surname");
        jTextField_surname.setBorder(null);
        jTextField_surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_surnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_surnameFocusLost(evt);
            }
        });
        jTextField_surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_surnameKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 300, 30));

        jSeparator9.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator9.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, 300, 10));

        jLabel_homeTown.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_homeTown.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_homeTown.setText("HOME TOWN:");
        jPanel_addAthlete.add(jLabel_homeTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jTextField_homeTown.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_homeTown.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_homeTown.setText("Enter the home town");
        jTextField_homeTown.setBorder(null);
        jTextField_homeTown.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_homeTownFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_homeTownFocusLost(evt);
            }
        });
        jTextField_homeTown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_homeTownKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_homeTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 300, 30));

        jSeparator10.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator10.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 300, 10));

        jLabel_address.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_address.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_address.setText("ADDRESS:");
        jPanel_addAthlete.add(jLabel_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, -1, -1));

        jTextField_address.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_address.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_address.setText("Enter the address");
        jTextField_address.setBorder(null);
        jTextField_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_addressFocusLost(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 300, 30));

        jSeparator11.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator11.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 300, 10));

        jLabel_birthDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_birthDate.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_birthDate.setText("BIRTH DATE:");
        jPanel_addAthlete.add(jLabel_birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, 20));

        jLabel_email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_email.setText("EMAIL:");
        jPanel_addAthlete.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, -1, 20));

        jTextField_email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_email.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_email.setText("e.g. example@gmail.com");
        jTextField_email.setBorder(null);
        jTextField_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusLost(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 300, 30));

        jSeparator13.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator13.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 300, 10));

        jLabel_favDiscipline.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_favDiscipline.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_favDiscipline.setText("FAVOURITE DISCIPLINE:");
        jPanel_addAthlete.add(jLabel_favDiscipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        jTextField_favDiscipline.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_favDiscipline.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_favDiscipline.setText("Enter the favourite discipline");
        jTextField_favDiscipline.setBorder(null);
        jTextField_favDiscipline.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_favDisciplineFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_favDisciplineFocusLost(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_favDiscipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 300, 30));

        jSeparator14.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator14.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 300, 10));

        jLabel_personalBest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_personalBest.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_personalBest.setText("PERSONAL BEST:");
        jPanel_addAthlete.add(jLabel_personalBest, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, -1, -1));

        jTextField_personalBest.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_personalBest.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_personalBest.setText("Enter the personal best");
        jTextField_personalBest.setBorder(null);
        jTextField_personalBest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_personalBestFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_personalBestFocusLost(evt);
            }
        });
        jTextField_personalBest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_personalBestKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_personalBest, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 460, 300, 30));

        jSeparator15.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator15.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 300, 10));

        jLabel_numMedals.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_numMedals.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_numMedals.setText("NUMBER OF MEDALS:");
        jPanel_addAthlete.add(jLabel_numMedals, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, -1));

        jTextField_numMedals.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_numMedals.setForeground(new java.awt.Color(52, 50, 46));
        jTextField_numMedals.setText("Enter the number of medals");
        jTextField_numMedals.setBorder(null);
        jTextField_numMedals.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_numMedalsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_numMedalsFocusLost(evt);
            }
        });
        jTextField_numMedals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numMedalsKeyTyped(evt);
            }
        });
        jPanel_addAthlete.add(jTextField_numMedals, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 300, 30));

        jSeparator16.setBackground(new java.awt.Color(52, 50, 46));
        jSeparator16.setForeground(new java.awt.Color(52, 50, 46));
        jPanel_addAthlete.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 300, 10));

        jLabel_team.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_team.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_team.setText("TEAM:");
        jPanel_addAthlete.add(jLabel_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, -1, -1));
        jPanel_addAthlete.add(jXDatePicker_birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 300, 30));

        jPanel_addAthlete.add(jComboBox_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_addAthlete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_addAthlete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_countryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_countryFocusGained
        if(jTextField_country.getText().equals("Enter the country"))
        {
            jTextField_country.setText("");
            jTextField_country.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_countryFocusGained

    private void jTextField_countryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_countryFocusLost
        if(jTextField_country.getText().equals(""))
        {
            jTextField_country.setText("Enter the country");
        }
    }//GEN-LAST:event_jTextField_countryFocusLost

    private void jTextField_nationalityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nationalityFocusGained
        if(jTextField_nationality.getText().equals("Enter the nationality"))
        {
            jTextField_nationality.setText("");
            jTextField_nationality.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_nationalityFocusGained

    private void jTextField_nationalityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nationalityFocusLost
        if(jTextField_nationality.getText().equals(""))
        {
            jTextField_nationality.setText("Enter the nationality");
        }
    }//GEN-LAST:event_jTextField_nationalityFocusLost

    private void jTextField_phoneNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phoneNumFocusGained
        if(jTextField_phoneNum.getText().equals("Enter the phone number"))
        {
            jTextField_phoneNum.setText("");
            jTextField_phoneNum.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_phoneNumFocusGained

    private void jTextField_phoneNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_phoneNumFocusLost
        if(jTextField_phoneNum.getText().equals(""))
        {
            jTextField_phoneNum.setText("Enter the phone number");
        }
    }//GEN-LAST:event_jTextField_phoneNumFocusLost

    private void jTextField_seasonBestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_seasonBestFocusGained
        if(jTextField_seasonBest.getText().equals("Enter the season best"))
        {
            jTextField_seasonBest.setText("");
            jTextField_seasonBest.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_seasonBestFocusGained

    private void jTextField_seasonBestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_seasonBestFocusLost
        if(jTextField_seasonBest.getText().equals(""))
        {
            jTextField_seasonBest.setText("Enter the season best");
        }
    }//GEN-LAST:event_jTextField_seasonBestFocusLost

    private void jTextField_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_idFocusGained
        if(jTextField_id.getText().equals("e.g. 78451256M"))
        {
            jTextField_id.setText("");
            jTextField_id.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_idFocusGained

    private void jTextField_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_idFocusLost
        if(jTextField_id.getText().equals(""))
        {
            jTextField_id.setText("e.g. 78451256M");
        }
    }//GEN-LAST:event_jTextField_idFocusLost

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jTextField_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusGained
        if(jTextField_name.getText().equals("Enter the name"))
        {
            jTextField_name.setText("");
            jTextField_name.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_nameFocusGained

    private void jTextField_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusLost
        if(jTextField_name.getText().equals(""))
        {
            jTextField_name.setText("Enter the name");
        }
    }//GEN-LAST:event_jTextField_nameFocusLost

    private void jTextField_surnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_surnameFocusGained
        if(jTextField_surname.getText().equals("Enter the surname"))
        {
            jTextField_surname.setText("");
            jTextField_surname.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_surnameFocusGained

    private void jTextField_surnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_surnameFocusLost
        if(jTextField_surname.getText().equals(""))
        {
            jTextField_surname.setText("Enter the surname");
        }
    }//GEN-LAST:event_jTextField_surnameFocusLost

    private void jTextField_homeTownFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_homeTownFocusGained
        if(jTextField_homeTown.getText().equals("Enter the home town"))
        {
            jTextField_homeTown.setText("");
            jTextField_homeTown.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_homeTownFocusGained

    private void jTextField_homeTownFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_homeTownFocusLost
        if(jTextField_homeTown.getText().equals(""))
        {
            jTextField_homeTown.setText("Enter the home town");
        }
    }//GEN-LAST:event_jTextField_homeTownFocusLost

    private void jTextField_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addressFocusGained
        if(jTextField_address.getText().equals("Enter the address"))
        {
            jTextField_address.setText("");
            jTextField_address.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_addressFocusGained

    private void jTextField_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addressFocusLost
        if(jTextField_address.getText().equals(""))
        {
            jTextField_address.setText("Enter the address");
        }
    }//GEN-LAST:event_jTextField_addressFocusLost

    private void jTextField_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusGained
        if(jTextField_email.getText().equals("e.g. example@gmail.com"))
        {
            jTextField_email.setText("");
            jTextField_email.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_emailFocusGained

    private void jTextField_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusLost
        if(jTextField_email.getText().equals(""))
        {
            jTextField_email.setText("e.g. example@gmail.com");
        }
    }//GEN-LAST:event_jTextField_emailFocusLost

    private void jTextField_favDisciplineFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_favDisciplineFocusGained
        if(jTextField_favDiscipline.getText().equals("Enter the favourite discipline"))
        {
            jTextField_favDiscipline.setText("");
            jTextField_favDiscipline.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_favDisciplineFocusGained

    private void jTextField_favDisciplineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_favDisciplineFocusLost
        if(jTextField_favDiscipline.getText().equals(""))
        {
            jTextField_favDiscipline.setText("Enter the favourite discipline");
        }
    }//GEN-LAST:event_jTextField_favDisciplineFocusLost

    private void jTextField_personalBestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_personalBestFocusGained
        if(jTextField_personalBest.getText().equals("Enter the personal best"))
        {
            jTextField_personalBest.setText("");
            jTextField_personalBest.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_personalBestFocusGained

    private void jTextField_personalBestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_personalBestFocusLost
        if(jTextField_personalBest.getText().equals(""))
        {
            jTextField_personalBest.setText("Enter the personal best");
        }
    }//GEN-LAST:event_jTextField_personalBestFocusLost

    private void jTextField_numMedalsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_numMedalsFocusGained
        if(jTextField_numMedals.getText().equals("Enter the number of medals"))
        {
            jTextField_numMedals.setText("");
            jTextField_numMedals.setCaretColor(Color.decode("#34322e"));
        }
    }//GEN-LAST:event_jTextField_numMedalsFocusGained

    private void jTextField_numMedalsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_numMedalsFocusLost
        if(jTextField_numMedals.getText().equals(""))
        {
            jTextField_numMedals.setText("Enter the number of medals");
        }
    }//GEN-LAST:event_jTextField_numMedalsFocusLost

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        jTextField_country.setText("Enter the country");
        jTextField_nationality.setText("Enter the nationality");
        jTextField_phoneNum.setText("Enter the phone number");
        jTextField_id.setText("e.g. 78451256M");
        jTextField_name.setText("Enter the name");
        jTextField_surname.setText("Enter the surname");
        jTextField_homeTown.setText("Enter the home town");
        jTextField_address.setText("Enter the address");
        jTextField_email.setText("e.g. example@gmail.com");
        jTextField_numMedals.setText("Enter the number of medals");
        jTextField_personalBest.setText("Enter the personal best");
        jTextField_seasonBest.setText("Enter the season best");
        jTextField_favDiscipline.setText("Enter the favourite discipline");
        jXDatePicker_birthDate.setDate(null);
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jTextField_numMedalsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numMedalsKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_numMedalsKeyTyped

    private void jTextField_personalBestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_personalBestKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown())
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_personalBestKeyTyped

    private void jTextField_seasonBestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_seasonBestKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown())
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_seasonBestKeyTyped

    private void jTextField_phoneNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneNumKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c) && !evt.isAltDown())
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_phoneNumKeyTyped

    private void jTextField_nationalityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nationalityKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isLetter(c)) && (c != KeyEvent.VK_BACK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_nationalityKeyTyped

    private void jTextField_homeTownKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_homeTownKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isLetter(c)) && (c != KeyEvent.VK_BACK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_homeTownKeyTyped

    private void jTextField_countryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_countryKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isLetter(c)) && (c != KeyEvent.VK_BACK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_countryKeyTyped

    private void jTextField_surnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_surnameKeyTyped
        char c = evt.getKeyChar();
        if(Character.isDigit(c) && !evt.isAltDown())
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_surnameKeyTyped

    private void jTextField_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isLetter(c)) && (c != KeyEvent.VK_BACK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_nameKeyTyped

    private void jTextField_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idKeyTyped
        char c = evt.getKeyChar();
        int length = jTextField_id.getText().length();
        
        if(length < 8)
        {
            if(!(Character.isDigit(c)) && (c != KeyEvent.VK_BACK_SPACE))
            {
                getToolkit().beep();
                evt.consume();
            }
        }
        
        else if(length == 8)
        {
            if(!(Character.isLetter(c)) && (c != KeyEvent.VK_BACK_SPACE))
            {
                getToolkit().beep();
                evt.consume();
            }
        }
        else if(length > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_idKeyTyped

    int xMouse;
    int yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_reset;
    public javax.swing.JButton jButton_save;
    public javax.swing.JComboBox<String> jComboBox_team;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_birthDate;
    private javax.swing.JLabel jLabel_country;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_favDiscipline;
    private javax.swing.JLabel jLabel_homeTown;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_nationality;
    private javax.swing.JLabel jLabel_numMedals;
    private javax.swing.JLabel jLabel_personalBest;
    private javax.swing.JLabel jLabel_phoneNum;
    private javax.swing.JLabel jLabel_seasonBest;
    private javax.swing.JLabel jLabel_surname;
    private javax.swing.JLabel jLabel_team;
    private javax.swing.JLabel jLabel_viewTitle;
    private javax.swing.JPanel jPanel_addAthlete;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField jTextField_address;
    public javax.swing.JTextField jTextField_country;
    public javax.swing.JTextField jTextField_email;
    public javax.swing.JTextField jTextField_favDiscipline;
    public javax.swing.JTextField jTextField_homeTown;
    public javax.swing.JTextField jTextField_id;
    public javax.swing.JTextField jTextField_name;
    public javax.swing.JTextField jTextField_nationality;
    public javax.swing.JTextField jTextField_numMedals;
    public javax.swing.JTextField jTextField_personalBest;
    public javax.swing.JTextField jTextField_phoneNum;
    public javax.swing.JTextField jTextField_seasonBest;
    public javax.swing.JTextField jTextField_surname;
    public org.jdesktop.swingx.JXDatePicker jXDatePicker_birthDate;
    // End of variables declaration//GEN-END:variables
}
