/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Eider
 */
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
        jPanel_usernameLeft.setVisible(false);
        jLabel_rightArrow.setVisible(false);
        SetImageSize(29);
        timerSld();
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //setBounds(120, 80, screenSize.width - 260, screenSize.height - 220);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_mainPage = new javax.swing.JPanel();
        jPanel_leftMenu = new javax.swing.JPanel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_userIcon = new javax.swing.JLabel();
        jLabel_trackAndFieldIcon = new javax.swing.JLabel();
        jLabel_titleUp = new javax.swing.JLabel();
        jLabel_titleDown = new javax.swing.JLabel();
        jPanel_athlete = new javax.swing.JPanel();
        jLabel_leftMenuAth = new javax.swing.JLabel();
        jLabel_athleteIcon = new javax.swing.JLabel();
        jPanel_athletesLeft = new javax.swing.JPanel();
        jPanel_coach = new javax.swing.JPanel();
        jLabel_leftMenuCoach = new javax.swing.JLabel();
        jLabel_coachIcon = new javax.swing.JLabel();
        jPanel_coachesLeft = new javax.swing.JPanel();
        jPanel_competition = new javax.swing.JPanel();
        jLabel_leftMenuComp = new javax.swing.JLabel();
        jLabel_competitionIcon = new javax.swing.JLabel();
        jPanel_competitionsLeft = new javax.swing.JPanel();
        jPanel_discipline = new javax.swing.JPanel();
        jLabel_leftMenuDis = new javax.swing.JLabel();
        jLabel_disciplineIcon = new javax.swing.JLabel();
        jPanel_disciplinesLeft = new javax.swing.JPanel();
        jPanel_result = new javax.swing.JPanel();
        jLabel_leftMenuRs = new javax.swing.JLabel();
        jLabel_resultIcon = new javax.swing.JLabel();
        jPanel_resultsLeft = new javax.swing.JPanel();
        jPanel_schedule = new javax.swing.JPanel();
        jLabel_leftMenuSch = new javax.swing.JLabel();
        jLabel_scheduleIcon = new javax.swing.JLabel();
        jPanel_scheduleLeft = new javax.swing.JPanel();
        jPanel_team = new javax.swing.JPanel();
        jLabel_leftMenuTm = new javax.swing.JLabel();
        jLabel_teamIcon = new javax.swing.JLabel();
        jPanel_teamsLeft = new javax.swing.JPanel();
        jPanel_registration = new javax.swing.JPanel();
        jLabel_leftMenuReg = new javax.swing.JLabel();
        jLabel_registrationIcon = new javax.swing.JLabel();
        jPanel_registrationLeft = new javax.swing.JPanel();
        jLabel_rightArrow = new javax.swing.JLabel();
        jPanel_header = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jPanel_usernameLeft = new javax.swing.JPanel();
        jLabel_logOut = new javax.swing.JLabel();
        jLabel_logOutIcon = new javax.swing.JLabel();
        jPanel_imageSlider = new javax.swing.JPanel();
        jLabel_image = new javax.swing.JLabel();
        jPanel_resultRight = new javax.swing.JPanel();
        jLabel_rightPanelResults = new javax.swing.JLabel();
        jPanel_result1 = new javax.swing.JPanel();
        jLabel_result1DisciplineGender = new javax.swing.JLabel();
        jLabel_result1Athlete = new javax.swing.JLabel();
        jLabel_result1Time = new javax.swing.JLabel();
        jPanel_result2 = new javax.swing.JPanel();
        jLabel_result2DisciplineGender = new javax.swing.JLabel();
        jLabel_result2Athlete = new javax.swing.JLabel();
        jLabel_result2Time = new javax.swing.JLabel();
        jPanel_result3 = new javax.swing.JPanel();
        jLabel_result3DisciplineGender = new javax.swing.JLabel();
        jLabel_result3Athlete = new javax.swing.JLabel();
        jLabel_result3Time = new javax.swing.JLabel();
        jPanel_scheduleRight = new javax.swing.JPanel();
        jLabel_rightPanelSchedule = new javax.swing.JLabel();
        jPanel_schedule4 = new javax.swing.JPanel();
        jLabel_schedule4CompetitionDiscipline = new javax.swing.JLabel();
        jLabel_schedule4GnederRound = new javax.swing.JLabel();
        jLabel_schedule4Date = new javax.swing.JLabel();
        jPanel_schedule3 = new javax.swing.JPanel();
        jLabel_schedule3CompetitionDiscipline = new javax.swing.JLabel();
        jLabel_schedule3GnederRound = new javax.swing.JLabel();
        jLabel_schedule3Date = new javax.swing.JLabel();
        jPanel_schedule1 = new javax.swing.JPanel();
        jLabel_schedule1GnederRound = new javax.swing.JLabel();
        jLabel_schedule1CompetitionDiscipline = new javax.swing.JLabel();
        jLabel_schedule1Date = new javax.swing.JLabel();
        jPanel_schedule2 = new javax.swing.JPanel();
        jLabel_schedule2CompetitionDiscipline = new javax.swing.JLabel();
        jLabel_schedule2GnederRound = new javax.swing.JLabel();
        jLabel_schedule2Date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_mainPage.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_mainPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel_mainPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_leftMenu.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_leftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_username.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_username.setText("Admin");
        jLabel_username.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_usernameMouseClicked(evt);
            }
        });
        jPanel_leftMenu.add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 780, 130, 40));

        jLabel_userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_user.png"))); // NOI18N
        jPanel_leftMenu.add(jLabel_userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 780, 50, 40));

        jLabel_trackAndFieldIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_trackAndFieldIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/rsz_trackandfieldicon-_-_copia.png"))); // NOI18N
        jPanel_leftMenu.add(jLabel_trackAndFieldIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 140));

        jLabel_titleUp.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_titleUp.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_titleUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titleUp.setText("TRACK");
        jPanel_leftMenu.add(jLabel_titleUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, 30));

        jLabel_titleDown.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_titleDown.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_titleDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titleDown.setText("AND FIELD");
        jPanel_leftMenu.add(jLabel_titleDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 30));

        jPanel_athlete.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_athlete.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel_athlete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_athleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_athleteMouseExited(evt);
            }
        });
        jPanel_athlete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuAth.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuAth.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuAth.setText("ATHLETES");
        jLabel_leftMenuAth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuAth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuAthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuAthMouseExited(evt);
            }
        });
        jPanel_athlete.add(jLabel_leftMenuAth, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_athleteIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_athleteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_athlete.png"))); // NOI18N
        jPanel_athlete.add(jLabel_athleteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_athletesLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_athletesLeftLayout = new javax.swing.GroupLayout(jPanel_athletesLeft);
        jPanel_athletesLeft.setLayout(jPanel_athletesLeftLayout);
        jPanel_athletesLeftLayout.setHorizontalGroup(
            jPanel_athletesLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_athletesLeftLayout.setVerticalGroup(
            jPanel_athletesLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_athlete.add(jPanel_athletesLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_athlete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 390, -1));

        jPanel_coach.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_coach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_coachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_coachMouseExited(evt);
            }
        });
        jPanel_coach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuCoach.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuCoach.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuCoach.setText("COACHES");
        jLabel_leftMenuCoach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuCoach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuCoachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuCoachMouseExited(evt);
            }
        });
        jPanel_coach.add(jLabel_leftMenuCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_coachIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_coachIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_coach.png"))); // NOI18N
        jPanel_coach.add(jLabel_coachIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_coachesLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_coachesLeftLayout = new javax.swing.GroupLayout(jPanel_coachesLeft);
        jPanel_coachesLeft.setLayout(jPanel_coachesLeftLayout);
        jPanel_coachesLeftLayout.setHorizontalGroup(
            jPanel_coachesLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_coachesLeftLayout.setVerticalGroup(
            jPanel_coachesLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_coach.add(jPanel_coachesLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_coach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 390, 60));

        jPanel_competition.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_competition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_competitionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_competitionMouseExited(evt);
            }
        });
        jPanel_competition.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuComp.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuComp.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuComp.setText("COMPETITIONS");
        jLabel_leftMenuComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuCompMouseExited(evt);
            }
        });
        jPanel_competition.add(jLabel_leftMenuComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_competitionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_competitionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_stopwatch.png"))); // NOI18N
        jPanel_competition.add(jLabel_competitionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_competitionsLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_competitionsLeftLayout = new javax.swing.GroupLayout(jPanel_competitionsLeft);
        jPanel_competitionsLeft.setLayout(jPanel_competitionsLeftLayout);
        jPanel_competitionsLeftLayout.setHorizontalGroup(
            jPanel_competitionsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_competitionsLeftLayout.setVerticalGroup(
            jPanel_competitionsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_competition.add(jPanel_competitionsLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_competition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 390, 60));

        jPanel_discipline.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_discipline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_disciplineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_disciplineMouseExited(evt);
            }
        });
        jPanel_discipline.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuDis.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuDis.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuDis.setText("DISCIPLINES");
        jLabel_leftMenuDis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuDis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuDisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuDisMouseExited(evt);
            }
        });
        jPanel_discipline.add(jLabel_leftMenuDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_disciplineIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_disciplineIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_highJump.png"))); // NOI18N
        jPanel_discipline.add(jLabel_disciplineIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_disciplinesLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_disciplinesLeftLayout = new javax.swing.GroupLayout(jPanel_disciplinesLeft);
        jPanel_disciplinesLeft.setLayout(jPanel_disciplinesLeftLayout);
        jPanel_disciplinesLeftLayout.setHorizontalGroup(
            jPanel_disciplinesLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_disciplinesLeftLayout.setVerticalGroup(
            jPanel_disciplinesLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_discipline.add(jPanel_disciplinesLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_discipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 390, 60));

        jPanel_result.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_resultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_resultMouseExited(evt);
            }
        });
        jPanel_result.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuRs.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuRs.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuRs.setText("RESULTS");
        jLabel_leftMenuRs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuRs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuRsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuRsMouseExited(evt);
            }
        });
        jPanel_result.add(jLabel_leftMenuRs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_resultIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_result.png"))); // NOI18N
        jPanel_result.add(jLabel_resultIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_resultsLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_resultsLeftLayout = new javax.swing.GroupLayout(jPanel_resultsLeft);
        jPanel_resultsLeft.setLayout(jPanel_resultsLeftLayout);
        jPanel_resultsLeftLayout.setHorizontalGroup(
            jPanel_resultsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_resultsLeftLayout.setVerticalGroup(
            jPanel_resultsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_result.add(jPanel_resultsLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 390, 60));

        jPanel_schedule.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_scheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_scheduleMouseExited(evt);
            }
        });
        jPanel_schedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuSch.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuSch.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuSch.setText("SCHEDULE");
        jLabel_leftMenuSch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuSch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuSchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuSchMouseExited(evt);
            }
        });
        jPanel_schedule.add(jLabel_leftMenuSch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_scheduleIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_scheduleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_schedule.png"))); // NOI18N
        jPanel_schedule.add(jLabel_scheduleIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_scheduleLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_scheduleLeftLayout = new javax.swing.GroupLayout(jPanel_scheduleLeft);
        jPanel_scheduleLeft.setLayout(jPanel_scheduleLeftLayout);
        jPanel_scheduleLeftLayout.setHorizontalGroup(
            jPanel_scheduleLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_scheduleLeftLayout.setVerticalGroup(
            jPanel_scheduleLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_schedule.add(jPanel_scheduleLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 390, 60));

        jPanel_team.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_team.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_teamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_teamMouseExited(evt);
            }
        });
        jPanel_team.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuTm.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuTm.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuTm.setText("TEAMS");
        jLabel_leftMenuTm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuTm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuTmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuTmMouseExited(evt);
            }
        });
        jPanel_team.add(jLabel_leftMenuTm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_teamIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_teamIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_team.png"))); // NOI18N
        jPanel_team.add(jLabel_teamIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_teamsLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_teamsLeftLayout = new javax.swing.GroupLayout(jPanel_teamsLeft);
        jPanel_teamsLeft.setLayout(jPanel_teamsLeftLayout);
        jPanel_teamsLeftLayout.setHorizontalGroup(
            jPanel_teamsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_teamsLeftLayout.setVerticalGroup(
            jPanel_teamsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_team.add(jPanel_teamsLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 390, 60));

        jPanel_registration.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_registrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_registrationMouseExited(evt);
            }
        });
        jPanel_registration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuReg.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuReg.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuReg.setText("REGISTRATION");
        jLabel_leftMenuReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_leftMenuReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_leftMenuRegMouseExited(evt);
            }
        });
        jPanel_registration.add(jLabel_leftMenuReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_registrationIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registrationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_registration.png"))); // NOI18N
        jPanel_registration.add(jLabel_registrationIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_registrationLeft.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_registrationLeftLayout = new javax.swing.GroupLayout(jPanel_registrationLeft);
        jPanel_registrationLeft.setLayout(jPanel_registrationLeftLayout);
        jPanel_registrationLeftLayout.setHorizontalGroup(
            jPanel_registrationLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_registrationLeftLayout.setVerticalGroup(
            jPanel_registrationLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_registration.add(jPanel_registrationLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenu.add(jPanel_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 390, 60));

        jLabel_rightArrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_rightArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/34x34_rightArrow.png"))); // NOI18N
        jPanel_leftMenu.add(jLabel_rightArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 780, 60, 40));

        jPanel_mainPage.add(jPanel_leftMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 860));

        jPanel_header.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_header.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(52, 50, 46)));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_exit4.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 0, 50, 50));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_minimize_1.png"))); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 0, 50, 50));

        jPanel_mainPage.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, 50));

        jPanel_usernameLeft.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_usernameLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logOut.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_logOut.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_logOut.setText("Log Out");
        jLabel_logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_usernameLeft.add(jLabel_logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, 40));

        jLabel_logOutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logOutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_logout.png"))); // NOI18N
        jPanel_usernameLeft.add(jLabel_logOutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, 40));

        jPanel_mainPage.add(jPanel_usernameLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 420, 310));

        jPanel_imageSlider.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_imageSlider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_image.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel_imageSlider.add(jLabel_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 410));

        jPanel_mainPage.add(jPanel_imageSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 680, 450));

        jPanel_resultRight.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_resultRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_rightPanelResults.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_rightPanelResults.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_rightPanelResults.setText("LATEST RESULTS");
        jPanel_resultRight.add(jLabel_rightPanelResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 180, 30));

        jPanel_result1.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_result1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel_result1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_result1DisciplineGender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result1DisciplineGender.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result1DisciplineGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result1.add(jLabel_result1DisciplineGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 30));

        jLabel_result1Athlete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result1Athlete.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result1Athlete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result1.add(jLabel_result1Athlete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 30));

        jLabel_result1Time.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result1Time.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result1Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result1.add(jLabel_result1Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 80, 60));

        jPanel_resultRight.add(jPanel_result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 420, 100));

        jPanel_result2.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_result2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel_result2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_result2DisciplineGender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result2DisciplineGender.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result2DisciplineGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result2.add(jLabel_result2DisciplineGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 30));

        jLabel_result2Athlete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result2Athlete.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result2Athlete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result2.add(jLabel_result2Athlete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 30));

        jLabel_result2Time.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result2Time.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result2Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result2.add(jLabel_result2Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 80, 60));

        jPanel_resultRight.add(jPanel_result2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 420, 100));

        jPanel_result3.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_result3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel_result3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_result3DisciplineGender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result3DisciplineGender.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result3DisciplineGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result3.add(jLabel_result3DisciplineGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 30));

        jLabel_result3Athlete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result3Athlete.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result3Athlete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result3.add(jLabel_result3Athlete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 30));

        jLabel_result3Time.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_result3Time.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_result3Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_result3.add(jLabel_result3Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 80, 60));

        jPanel_resultRight.add(jPanel_result3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 420, 100));

        jPanel_mainPage.add(jPanel_resultRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, 510, 450));

        jPanel_scheduleRight.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_scheduleRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_rightPanelSchedule.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_rightPanelSchedule.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_rightPanelSchedule.setText("SCHEDULE");
        jPanel_scheduleRight.add(jLabel_rightPanelSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 40));

        jPanel_schedule4.setBackground(new java.awt.Color(210, 87, 34));
        jPanel_schedule4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 87, 34)));
        jPanel_schedule4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_schedule4CompetitionDiscipline.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule4CompetitionDiscipline.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_schedule4CompetitionDiscipline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule4.add(jLabel_schedule4CompetitionDiscipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 20));

        jLabel_schedule4GnederRound.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule4GnederRound.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_schedule4GnederRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule4.add(jLabel_schedule4GnederRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 44, 330, 20));

        jLabel_schedule4Date.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule4Date.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_schedule4Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule4.add(jLabel_schedule4Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, 40));

        jPanel_scheduleRight.add(jPanel_schedule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 540, 80));

        jPanel_schedule3.setBackground(new java.awt.Color(210, 87, 34));
        jPanel_schedule3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 87, 34)));
        jPanel_schedule3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_schedule3CompetitionDiscipline.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule3CompetitionDiscipline.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_schedule3CompetitionDiscipline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule3.add(jLabel_schedule3CompetitionDiscipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 20));

        jLabel_schedule3GnederRound.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule3GnederRound.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_schedule3GnederRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule3.add(jLabel_schedule3GnederRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 44, 330, 20));

        jLabel_schedule3Date.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule3Date.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_schedule3Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule3.add(jLabel_schedule3Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, 40));

        jPanel_scheduleRight.add(jPanel_schedule3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 540, 80));

        jPanel_schedule1.setBackground(new java.awt.Color(210, 87, 34));
        jPanel_schedule1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 87, 34)));
        jPanel_schedule1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_schedule1GnederRound.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule1GnederRound.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_schedule1GnederRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule1.add(jLabel_schedule1GnederRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 44, 330, 20));

        jLabel_schedule1CompetitionDiscipline.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule1CompetitionDiscipline.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_schedule1CompetitionDiscipline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule1.add(jLabel_schedule1CompetitionDiscipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 20));

        jLabel_schedule1Date.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule1Date.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_schedule1Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule1.add(jLabel_schedule1Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, 40));

        jPanel_scheduleRight.add(jPanel_schedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 540, 80));

        jPanel_schedule2.setBackground(new java.awt.Color(210, 87, 34));
        jPanel_schedule2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 87, 34)));
        jPanel_schedule2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_schedule2CompetitionDiscipline.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule2CompetitionDiscipline.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_schedule2CompetitionDiscipline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule2.add(jLabel_schedule2CompetitionDiscipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 20));

        jLabel_schedule2GnederRound.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule2GnederRound.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_schedule2GnederRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule2.add(jLabel_schedule2GnederRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 44, 330, 20));

        jLabel_schedule2Date.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_schedule2Date.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_schedule2Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_schedule2.add(jLabel_schedule2Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, 40));

        jPanel_scheduleRight.add(jPanel_schedule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 540, 80));

        jPanel_mainPage.add(jPanel_scheduleRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 1210, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_mainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_mainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    private void jLabel_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_usernameMouseClicked
        if(jPanel_usernameLeft.isVisible())
        {
            jPanel_usernameLeft.setVisible(false);
        }
        else
        {
            jPanel_usernameLeft.setVisible(true);
        }
        
        if(jLabel_rightArrow.isVisible())
        {
            jLabel_rightArrow.setVisible(false);
        }
        else
        {
            jLabel_rightArrow.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_usernameMouseClicked

    private void jPanel_athleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_athleteMouseEntered
        jPanel_athlete.setBackground(new Color(163, 67, 26));
        jPanel_athletesLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_athleteMouseEntered

    private void jPanel_athleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_athleteMouseExited
        jPanel_athlete.setBackground(new Color(52, 50, 46));
        jPanel_athletesLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_athleteMouseExited

    private void jPanel_coachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_coachMouseEntered
        jPanel_coach.setBackground(new Color(163, 67, 26));
        jPanel_coachesLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_coachMouseEntered

    private void jPanel_coachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_coachMouseExited
        jPanel_coach.setBackground(new Color(52, 50, 46));
        jPanel_coachesLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_coachMouseExited

    private void jPanel_competitionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_competitionMouseEntered
        jPanel_competition.setBackground(new Color(163, 67, 26));
        jPanel_competitionsLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_competitionMouseEntered

    private void jPanel_competitionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_competitionMouseExited
        jPanel_competition.setBackground(new Color(52, 50, 46));
        jPanel_competitionsLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_competitionMouseExited

    private void jPanel_disciplineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_disciplineMouseEntered
        jPanel_discipline.setBackground(new Color(163, 67, 26));
        jPanel_disciplinesLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_disciplineMouseEntered

    private void jPanel_disciplineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_disciplineMouseExited
        jPanel_discipline.setBackground(new Color(52, 50, 46));
        jPanel_disciplinesLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_disciplineMouseExited

    private void jPanel_resultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_resultMouseEntered
        jPanel_result.setBackground(new Color(163, 67, 26));
        jPanel_resultsLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_resultMouseEntered

    private void jPanel_resultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_resultMouseExited
        jPanel_result.setBackground(new Color(52, 50, 46));
        jPanel_resultsLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_resultMouseExited

    private void jPanel_scheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_scheduleMouseEntered
        jPanel_schedule.setBackground(new Color(163, 67, 26));
        jPanel_scheduleLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_scheduleMouseEntered

    private void jPanel_scheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_scheduleMouseExited
        jPanel_schedule.setBackground(new Color(52, 50, 46));
        jPanel_scheduleLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_scheduleMouseExited

    private void jPanel_teamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_teamMouseEntered
        jPanel_team.setBackground(new Color(163, 67, 26));
        jPanel_teamsLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_teamMouseEntered

    private void jPanel_teamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_teamMouseExited
        jPanel_team.setBackground(new Color(52, 50, 46));
        jPanel_teamsLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_teamMouseExited

    private void jPanel_registrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_registrationMouseEntered
        jPanel_registration.setBackground(new Color(163, 67, 26));
        jPanel_registrationLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_registrationMouseEntered

    private void jPanel_registrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_registrationMouseExited
        jPanel_registration.setBackground(new Color(52, 50, 46));
        jPanel_registrationLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_registrationMouseExited

    private void jLabel_leftMenuAthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuAthMouseEntered
        jPanel_athlete.setBackground(new Color(163, 67, 26));
        jPanel_athletesLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuAthMouseEntered

    private void jLabel_leftMenuAthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuAthMouseExited
        jPanel_athlete.setBackground(new Color(52, 50, 46));
        jPanel_athletesLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuAthMouseExited

    private void jLabel_leftMenuCoachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuCoachMouseEntered
        jPanel_coach.setBackground(new Color(163, 67, 26));
        jPanel_coachesLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuCoachMouseEntered

    private void jLabel_leftMenuCoachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuCoachMouseExited
        jPanel_coach.setBackground(new Color(52, 50, 46));
        jPanel_coachesLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuCoachMouseExited

    private void jLabel_leftMenuCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuCompMouseEntered
        jPanel_competition.setBackground(new Color(163, 67, 26));
        jPanel_competitionsLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuCompMouseEntered

    private void jLabel_leftMenuCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuCompMouseExited
        jPanel_competition.setBackground(new Color(52, 50, 46));
        jPanel_competitionsLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuCompMouseExited

    private void jLabel_leftMenuDisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuDisMouseEntered
        jPanel_discipline.setBackground(new Color(163, 67, 26));
        jPanel_disciplinesLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuDisMouseEntered

    private void jLabel_leftMenuDisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuDisMouseExited
        jPanel_discipline.setBackground(new Color(52, 50, 46));
        jPanel_disciplinesLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuDisMouseExited

    private void jLabel_leftMenuRsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuRsMouseEntered
        jPanel_result.setBackground(new Color(163, 67, 26));
        jPanel_resultsLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuRsMouseEntered

    private void jLabel_leftMenuRsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuRsMouseExited
        jPanel_result.setBackground(new Color(52, 50, 46));
        jPanel_resultsLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuRsMouseExited

    private void jLabel_leftMenuSchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuSchMouseEntered
        jPanel_schedule.setBackground(new Color(163, 67, 26));
        jPanel_scheduleLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuSchMouseEntered

    private void jLabel_leftMenuSchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuSchMouseExited
        jPanel_schedule.setBackground(new Color(52, 50, 46));
        jPanel_scheduleLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuSchMouseExited

    private void jLabel_leftMenuTmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuTmMouseEntered
        jPanel_team.setBackground(new Color(163, 67, 26));
        jPanel_teamsLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuTmMouseEntered

    private void jLabel_leftMenuTmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuTmMouseExited
        jPanel_team.setBackground(new Color(52, 50, 46));
        jPanel_teamsLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuTmMouseExited

    private void jLabel_leftMenuRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuRegMouseEntered
        jPanel_registration.setBackground(new Color(163, 67, 26));
        jPanel_registrationLeft.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jLabel_leftMenuRegMouseEntered

    private void jLabel_leftMenuRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_leftMenuRegMouseExited
        jPanel_registration.setBackground(new Color(52, 50, 46));
        jPanel_registrationLeft.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jLabel_leftMenuRegMouseExited


    // Timer methods
    public void SetImageSize(int i)
    {
        ImageIcon icon = new ImageIcon(imageList[i]);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(newImg);
        jLabel_image.setIcon(newImc);
    }
    
    public void timerSld()
    {
        tm = new Timer(5000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                SetImageSize(x);
                x += 1;
                if(x >= imageList.length)
                {
                    x = 0;
                }
            }
        });
        tm.start();
    }
  
    
    // Variables
    int xMouse;
    int yMouse;
    Timer tm;
    int x = 0;
    String[] imageList = {
        "src/View/Slider/4x100m_relay_women.png",
        "src/View/Slider/tripleJump_women.png",
        "src/View/Slider/RenaudLavillenie.png",
        "src/View/Slider/100mHurdles_women.png",
        "src/View/Slider/10000_women.png",
        "src/View/Slider/javelinThrow_men.png",
        "src/View/Slider/1500_women.png",
        "src/View/Slider/3000_steeplechase_women.png",
        "src/View/Slider/400mHurdles_women.png",
        "src/View/Slider/Obiri.png",
        "src/View/Slider/110mHurdles_men.png",
        "src/View/Slider/800m_women.png",
        "src/View/Slider/5000m_men.png",
        "src/View/Slider/4x400m_relay_men.png",
        "src/View/Slider/decathlon_eaton.png",
        "src/View/Slider/400m_men.png",
        "src/View/Slider/halfMarathon_men.png",
        "src/View/Slider/hammerThrow_women.png",
        "src/View/Slider/highJump_men.png",
        "src/View/Slider/javelinThrow_diamondLeague.png",
        "src/View/Slider/800m_men.png",
        "src/View/Slider/3000_steeplechase_men.png",
        "src/View/Slider/longJump_women.png",
        "src/View/Slider/EmmaCoburn.jpg",
        "src/View/Slider/marathon_women.png",
        "src/View/Slider/poleVault_women.png",
        "src/View/Slider/100m_women.png",
        "src/View/Slider/shotPut_men.png",
        "src/View/Slider/tripleJump_men.png",
        "src/View/Slider/OmarMcLeod.jpg"
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_athleteIcon;
    private javax.swing.JLabel jLabel_coachIcon;
    private javax.swing.JLabel jLabel_competitionIcon;
    private javax.swing.JLabel jLabel_disciplineIcon;
    public javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_image;
    public javax.swing.JLabel jLabel_leftMenuAth;
    public javax.swing.JLabel jLabel_leftMenuCoach;
    public javax.swing.JLabel jLabel_leftMenuComp;
    public javax.swing.JLabel jLabel_leftMenuDis;
    public javax.swing.JLabel jLabel_leftMenuReg;
    public javax.swing.JLabel jLabel_leftMenuRs;
    public javax.swing.JLabel jLabel_leftMenuSch;
    public javax.swing.JLabel jLabel_leftMenuTm;
    public javax.swing.JLabel jLabel_logOut;
    private javax.swing.JLabel jLabel_logOutIcon;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_registrationIcon;
    public javax.swing.JLabel jLabel_result1Athlete;
    public javax.swing.JLabel jLabel_result1DisciplineGender;
    public javax.swing.JLabel jLabel_result1Time;
    public javax.swing.JLabel jLabel_result2Athlete;
    public javax.swing.JLabel jLabel_result2DisciplineGender;
    public javax.swing.JLabel jLabel_result2Time;
    public javax.swing.JLabel jLabel_result3Athlete;
    public javax.swing.JLabel jLabel_result3DisciplineGender;
    public javax.swing.JLabel jLabel_result3Time;
    private javax.swing.JLabel jLabel_resultIcon;
    public javax.swing.JLabel jLabel_rightArrow;
    private javax.swing.JLabel jLabel_rightPanelResults;
    private javax.swing.JLabel jLabel_rightPanelSchedule;
    public javax.swing.JLabel jLabel_schedule1CompetitionDiscipline;
    public javax.swing.JLabel jLabel_schedule1Date;
    public javax.swing.JLabel jLabel_schedule1GnederRound;
    public javax.swing.JLabel jLabel_schedule2CompetitionDiscipline;
    public javax.swing.JLabel jLabel_schedule2Date;
    public javax.swing.JLabel jLabel_schedule2GnederRound;
    public javax.swing.JLabel jLabel_schedule3CompetitionDiscipline;
    public javax.swing.JLabel jLabel_schedule3Date;
    public javax.swing.JLabel jLabel_schedule3GnederRound;
    public javax.swing.JLabel jLabel_schedule4CompetitionDiscipline;
    public javax.swing.JLabel jLabel_schedule4Date;
    public javax.swing.JLabel jLabel_schedule4GnederRound;
    private javax.swing.JLabel jLabel_scheduleIcon;
    private javax.swing.JLabel jLabel_teamIcon;
    private javax.swing.JLabel jLabel_titleDown;
    private javax.swing.JLabel jLabel_titleUp;
    private javax.swing.JLabel jLabel_trackAndFieldIcon;
    private javax.swing.JLabel jLabel_userIcon;
    public javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel_athlete;
    private javax.swing.JPanel jPanel_athletesLeft;
    private javax.swing.JPanel jPanel_coach;
    private javax.swing.JPanel jPanel_coachesLeft;
    private javax.swing.JPanel jPanel_competition;
    private javax.swing.JPanel jPanel_competitionsLeft;
    private javax.swing.JPanel jPanel_discipline;
    private javax.swing.JPanel jPanel_disciplinesLeft;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_imageSlider;
    private javax.swing.JPanel jPanel_leftMenu;
    private javax.swing.JPanel jPanel_mainPage;
    private javax.swing.JPanel jPanel_registration;
    private javax.swing.JPanel jPanel_registrationLeft;
    private javax.swing.JPanel jPanel_result;
    private javax.swing.JPanel jPanel_result1;
    private javax.swing.JPanel jPanel_result2;
    private javax.swing.JPanel jPanel_result3;
    private javax.swing.JPanel jPanel_resultRight;
    private javax.swing.JPanel jPanel_resultsLeft;
    private javax.swing.JPanel jPanel_schedule;
    private javax.swing.JPanel jPanel_schedule1;
    private javax.swing.JPanel jPanel_schedule2;
    private javax.swing.JPanel jPanel_schedule3;
    private javax.swing.JPanel jPanel_schedule4;
    private javax.swing.JPanel jPanel_scheduleLeft;
    private javax.swing.JPanel jPanel_scheduleRight;
    private javax.swing.JPanel jPanel_team;
    private javax.swing.JPanel jPanel_teamsLeft;
    public javax.swing.JPanel jPanel_usernameLeft;
    // End of variables declaration//GEN-END:variables
}
