/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Eider
 */
public class mainPageGuest extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public mainPageGuest() {
        initComponents();
        jPanel_usernameLeftGuest.setVisible(false);
        jLabel_rightArrowGuest.setVisible(false);
        SetImageSize(29);
        timerSld();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_mainPageGuest = new javax.swing.JPanel();
        jPanel_leftMenuGuest = new javax.swing.JPanel();
        jLabel_usernameGuest = new javax.swing.JLabel();
        jLabel_userIconGuest = new javax.swing.JLabel();
        jLabel_trackAndFieldIconGuest = new javax.swing.JLabel();
        jLabel_titleUpGuest = new javax.swing.JLabel();
        jLabel_titleDownGuest = new javax.swing.JLabel();
        jPanel_athleteGuest = new javax.swing.JPanel();
        jLabel_leftMenuAthGuest = new javax.swing.JLabel();
        jLabel_athleteIconGuest = new javax.swing.JLabel();
        jPanel_athletesLeftGuest = new javax.swing.JPanel();
        jPanel_coachGuest = new javax.swing.JPanel();
        jLabel_leftMenuCoachGuest = new javax.swing.JLabel();
        jLabel_coachIconGuest = new javax.swing.JLabel();
        jPanel_coachesLeftGuest = new javax.swing.JPanel();
        jPanel_competitionGuest = new javax.swing.JPanel();
        jLabel_leftMenuCompGuest = new javax.swing.JLabel();
        jLabel_competitionIconGuest = new javax.swing.JLabel();
        jPanel_competitionsLeftGuest = new javax.swing.JPanel();
        jPanel_disciplineGuest = new javax.swing.JPanel();
        jLabel_leftMenuDisGuest = new javax.swing.JLabel();
        jLabel_disciplineIconGuest = new javax.swing.JLabel();
        jPanel_disciplinesLeftGuest = new javax.swing.JPanel();
        jPanel_resultGuest = new javax.swing.JPanel();
        jLabel_leftMenuRsGuest = new javax.swing.JLabel();
        jLabel_resultIconGuest = new javax.swing.JLabel();
        jPanel_resultsLeftGuest = new javax.swing.JPanel();
        jPanel_scheduleGuest = new javax.swing.JPanel();
        jLabel_leftMenuSchGuest = new javax.swing.JLabel();
        jLabel_scheduleIconGuest = new javax.swing.JLabel();
        jPanel_scheduleLeftGuest = new javax.swing.JPanel();
        jPanel_teamGuest = new javax.swing.JPanel();
        jLabel_leftMenuTmGuest = new javax.swing.JLabel();
        jLabel_teamIconGuest = new javax.swing.JLabel();
        jPanel_teamsLeftGuest = new javax.swing.JPanel();
        jPanel_registrationGuest = new javax.swing.JPanel();
        jLabel_leftMenuRegGuest = new javax.swing.JLabel();
        jLabel_registrationIconGuest = new javax.swing.JLabel();
        jPanel_registrationLeftGuest = new javax.swing.JPanel();
        jLabel_rightArrowGuest = new javax.swing.JLabel();
        jPanel_headerGuest = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jPanel_usernameLeftGuest = new javax.swing.JPanel();
        jLabel_logOutGuest = new javax.swing.JLabel();
        jLabel_logOutIconGuest = new javax.swing.JLabel();
        jPanel_imageSliderGuest = new javax.swing.JPanel();
        jLabel_imageGuest = new javax.swing.JLabel();
        jPanel_resultRightGuest = new javax.swing.JPanel();
        jLabel_rightPanelResultsGuest = new javax.swing.JLabel();
        jPanel_scheduleRightGuest = new javax.swing.JPanel();
        jLabel_rightPanelScheduleGuest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_mainPageGuest.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_mainPageGuest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel_mainPageGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_leftMenuGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_leftMenuGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_usernameGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_usernameGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_usernameGuest.setText("Guest");
        jLabel_usernameGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_usernameGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_usernameGuestMouseClicked(evt);
            }
        });
        jPanel_leftMenuGuest.add(jLabel_usernameGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 780, 130, 40));

        jLabel_userIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_userIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_user.png")); // NOI18N
        jPanel_leftMenuGuest.add(jLabel_userIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 780, 50, 40));

        jLabel_trackAndFieldIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_trackAndFieldIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\rsz_trackandfieldicon-_-_copia.png")); // NOI18N
        jPanel_leftMenuGuest.add(jLabel_trackAndFieldIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 140));

        jLabel_titleUpGuest.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_titleUpGuest.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_titleUpGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titleUpGuest.setText("TRACK");
        jPanel_leftMenuGuest.add(jLabel_titleUpGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, 30));

        jLabel_titleDownGuest.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_titleDownGuest.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_titleDownGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titleDownGuest.setText("AND FIELD");
        jPanel_leftMenuGuest.add(jLabel_titleDownGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 30));

        jPanel_athleteGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_athleteGuest.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel_athleteGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_athleteGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_athleteGuestMouseExited(evt);
            }
        });
        jPanel_athleteGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuAthGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuAthGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuAthGuest.setText("ATHLETES");
        jLabel_leftMenuAthGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_athleteGuest.add(jLabel_leftMenuAthGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_athleteIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_athleteIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_athlete.png")); // NOI18N
        jPanel_athleteGuest.add(jLabel_athleteIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_athletesLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_athletesLeftGuestLayout = new javax.swing.GroupLayout(jPanel_athletesLeftGuest);
        jPanel_athletesLeftGuest.setLayout(jPanel_athletesLeftGuestLayout);
        jPanel_athletesLeftGuestLayout.setHorizontalGroup(
            jPanel_athletesLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_athletesLeftGuestLayout.setVerticalGroup(
            jPanel_athletesLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_athleteGuest.add(jPanel_athletesLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_athleteGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 390, -1));

        jPanel_coachGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_coachGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_coachGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_coachGuestMouseExited(evt);
            }
        });
        jPanel_coachGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuCoachGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuCoachGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuCoachGuest.setText("COACHES");
        jLabel_leftMenuCoachGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_coachGuest.add(jLabel_leftMenuCoachGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_coachIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_coachIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_coach.png")); // NOI18N
        jPanel_coachGuest.add(jLabel_coachIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_coachesLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_coachesLeftGuestLayout = new javax.swing.GroupLayout(jPanel_coachesLeftGuest);
        jPanel_coachesLeftGuest.setLayout(jPanel_coachesLeftGuestLayout);
        jPanel_coachesLeftGuestLayout.setHorizontalGroup(
            jPanel_coachesLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_coachesLeftGuestLayout.setVerticalGroup(
            jPanel_coachesLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_coachGuest.add(jPanel_coachesLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_coachGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 390, 60));

        jPanel_competitionGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_competitionGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_competitionGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_competitionGuestMouseExited(evt);
            }
        });
        jPanel_competitionGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuCompGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuCompGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuCompGuest.setText("COMPETITIONS");
        jLabel_leftMenuCompGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_competitionGuest.add(jLabel_leftMenuCompGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_competitionIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_competitionIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_stopwatch.png")); // NOI18N
        jPanel_competitionGuest.add(jLabel_competitionIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_competitionsLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_competitionsLeftGuestLayout = new javax.swing.GroupLayout(jPanel_competitionsLeftGuest);
        jPanel_competitionsLeftGuest.setLayout(jPanel_competitionsLeftGuestLayout);
        jPanel_competitionsLeftGuestLayout.setHorizontalGroup(
            jPanel_competitionsLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_competitionsLeftGuestLayout.setVerticalGroup(
            jPanel_competitionsLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_competitionGuest.add(jPanel_competitionsLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_competitionGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 390, 60));

        jPanel_disciplineGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_disciplineGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_disciplineGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_disciplineGuestMouseExited(evt);
            }
        });
        jPanel_disciplineGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuDisGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuDisGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuDisGuest.setText("DISCIPLINES");
        jLabel_leftMenuDisGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_disciplineGuest.add(jLabel_leftMenuDisGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_disciplineIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_disciplineIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\Disciplines\\40x40_highJump.png")); // NOI18N
        jPanel_disciplineGuest.add(jLabel_disciplineIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_disciplinesLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_disciplinesLeftGuestLayout = new javax.swing.GroupLayout(jPanel_disciplinesLeftGuest);
        jPanel_disciplinesLeftGuest.setLayout(jPanel_disciplinesLeftGuestLayout);
        jPanel_disciplinesLeftGuestLayout.setHorizontalGroup(
            jPanel_disciplinesLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_disciplinesLeftGuestLayout.setVerticalGroup(
            jPanel_disciplinesLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_disciplineGuest.add(jPanel_disciplinesLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_disciplineGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 390, 60));

        jPanel_resultGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_resultGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_resultGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_resultGuestMouseExited(evt);
            }
        });
        jPanel_resultGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuRsGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuRsGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuRsGuest.setText("RESULTS");
        jLabel_leftMenuRsGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_resultGuest.add(jLabel_leftMenuRsGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_resultIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_result.png")); // NOI18N
        jPanel_resultGuest.add(jLabel_resultIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_resultsLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_resultsLeftGuestLayout = new javax.swing.GroupLayout(jPanel_resultsLeftGuest);
        jPanel_resultsLeftGuest.setLayout(jPanel_resultsLeftGuestLayout);
        jPanel_resultsLeftGuestLayout.setHorizontalGroup(
            jPanel_resultsLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_resultsLeftGuestLayout.setVerticalGroup(
            jPanel_resultsLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_resultGuest.add(jPanel_resultsLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_resultGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 390, 60));

        jPanel_scheduleGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_scheduleGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_scheduleGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_scheduleGuestMouseExited(evt);
            }
        });
        jPanel_scheduleGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuSchGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuSchGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuSchGuest.setText("SCHEDULE");
        jLabel_leftMenuSchGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_scheduleGuest.add(jLabel_leftMenuSchGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_scheduleIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_scheduleIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_schedule.png")); // NOI18N
        jPanel_scheduleGuest.add(jLabel_scheduleIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_scheduleLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_scheduleLeftGuestLayout = new javax.swing.GroupLayout(jPanel_scheduleLeftGuest);
        jPanel_scheduleLeftGuest.setLayout(jPanel_scheduleLeftGuestLayout);
        jPanel_scheduleLeftGuestLayout.setHorizontalGroup(
            jPanel_scheduleLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_scheduleLeftGuestLayout.setVerticalGroup(
            jPanel_scheduleLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_scheduleGuest.add(jPanel_scheduleLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_scheduleGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 390, 60));

        jPanel_teamGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_teamGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_teamGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_teamGuestMouseExited(evt);
            }
        });
        jPanel_teamGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuTmGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuTmGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuTmGuest.setText("TEAMS");
        jLabel_leftMenuTmGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_teamGuest.add(jLabel_leftMenuTmGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_teamIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_teamIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_team.png")); // NOI18N
        jPanel_teamGuest.add(jLabel_teamIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_teamsLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_teamsLeftGuestLayout = new javax.swing.GroupLayout(jPanel_teamsLeftGuest);
        jPanel_teamsLeftGuest.setLayout(jPanel_teamsLeftGuestLayout);
        jPanel_teamsLeftGuestLayout.setHorizontalGroup(
            jPanel_teamsLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_teamsLeftGuestLayout.setVerticalGroup(
            jPanel_teamsLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_teamGuest.add(jPanel_teamsLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_teamGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 390, 60));

        jPanel_registrationGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_registrationGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_registrationGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_registrationGuestMouseExited(evt);
            }
        });
        jPanel_registrationGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_leftMenuRegGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_leftMenuRegGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_leftMenuRegGuest.setText("REGISTRATION");
        jLabel_leftMenuRegGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_registrationGuest.add(jLabel_leftMenuRegGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 60));

        jLabel_registrationIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registrationIconGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\40x40_registration.png")); // NOI18N
        jPanel_registrationGuest.add(jLabel_registrationIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 40));

        jPanel_registrationLeftGuest.setBackground(new java.awt.Color(52, 50, 46));

        javax.swing.GroupLayout jPanel_registrationLeftGuestLayout = new javax.swing.GroupLayout(jPanel_registrationLeftGuest);
        jPanel_registrationLeftGuest.setLayout(jPanel_registrationLeftGuestLayout);
        jPanel_registrationLeftGuestLayout.setHorizontalGroup(
            jPanel_registrationLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel_registrationLeftGuestLayout.setVerticalGroup(
            jPanel_registrationLeftGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel_registrationGuest.add(jPanel_registrationLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 60));

        jPanel_leftMenuGuest.add(jPanel_registrationGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 390, 60));

        jLabel_rightArrowGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_rightArrowGuest.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\40x40\\34x34_rightArrow.png")); // NOI18N
        jPanel_leftMenuGuest.add(jLabel_rightArrowGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 780, 60, 40));

        jPanel_mainPageGuest.add(jPanel_leftMenuGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 860));

        jPanel_headerGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_headerGuest.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(52, 50, 46)));
        jPanel_headerGuest.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerGuestMouseDragged(evt);
            }
        });
        jPanel_headerGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerGuestMousePressed(evt);
            }
        });
        jPanel_headerGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\30x30\\30x30_exit4.png")); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_headerGuest.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 0, 50, 50));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon("G:\\DAM\\Program\\Irudixak\\Icons\\Resized\\30x30\\30x30_minimize_1.png")); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_headerGuest.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 0, 50, 50));

        jPanel_mainPageGuest.add(jPanel_headerGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, 50));

        jPanel_usernameLeftGuest.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_usernameLeftGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logOutGuest.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_logOutGuest.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_logOutGuest.setText("Log Out");
        jPanel_usernameLeftGuest.add(jLabel_logOutGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, 40));

        jLabel_logOutIconGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logOutIconGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/40x40_logout.png"))); // NOI18N
        jPanel_usernameLeftGuest.add(jLabel_logOutIconGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, 40));

        jPanel_mainPageGuest.add(jPanel_usernameLeftGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 420, 310));

        jPanel_imageSliderGuest.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_imageSliderGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_imageGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_imageSliderGuest.add(jLabel_imageGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 410));

        jPanel_mainPageGuest.add(jPanel_imageSliderGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 680, 450));

        jPanel_resultRightGuest.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_resultRightGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_rightPanelResultsGuest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_rightPanelResultsGuest.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_rightPanelResultsGuest.setText("RESULTS");
        jPanel_resultRightGuest.add(jLabel_rightPanelResultsGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 40));

        jPanel_mainPageGuest.add(jPanel_resultRightGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, 510, 450));

        jPanel_scheduleRightGuest.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_scheduleRightGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_rightPanelScheduleGuest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_rightPanelScheduleGuest.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_rightPanelScheduleGuest.setText("SCHEDULE");
        jPanel_scheduleRightGuest.add(jLabel_rightPanelScheduleGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 40));

        jPanel_mainPageGuest.add(jPanel_scheduleRightGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 1210, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_mainPageGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_mainPageGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jPanel_headerGuestMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerGuestMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerGuestMouseDragged

    private void jPanel_headerGuestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerGuestMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerGuestMousePressed

    private void jLabel_usernameGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_usernameGuestMouseClicked
        if(jPanel_usernameLeftGuest.isVisible())
        {
            jPanel_usernameLeftGuest.setVisible(false);
        }
        else
        {
            jPanel_usernameLeftGuest.setVisible(true);
        }
        
        if(jLabel_rightArrowGuest.isVisible())
        {
            jLabel_rightArrowGuest.setVisible(false);
        }
        else
        {
            jLabel_rightArrowGuest.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_usernameGuestMouseClicked

    private void jPanel_athleteGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_athleteGuestMouseEntered
        jPanel_athleteGuest.setBackground(new Color(163, 67, 26));
        jPanel_athletesLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_athleteGuestMouseEntered

    private void jPanel_athleteGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_athleteGuestMouseExited
        jPanel_athleteGuest.setBackground(new Color(52, 50, 46));
        jPanel_athletesLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_athleteGuestMouseExited

    private void jPanel_coachGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_coachGuestMouseEntered
        jPanel_coachGuest.setBackground(new Color(163, 67, 26));
        jPanel_coachesLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_coachGuestMouseEntered

    private void jPanel_coachGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_coachGuestMouseExited
        jPanel_coachGuest.setBackground(new Color(52, 50, 46));
        jPanel_coachesLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_coachGuestMouseExited

    private void jPanel_competitionGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_competitionGuestMouseEntered
        jPanel_competitionGuest.setBackground(new Color(163, 67, 26));
        jPanel_competitionsLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_competitionGuestMouseEntered

    private void jPanel_competitionGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_competitionGuestMouseExited
        jPanel_competitionGuest.setBackground(new Color(52, 50, 46));
        jPanel_competitionsLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_competitionGuestMouseExited

    private void jPanel_disciplineGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_disciplineGuestMouseEntered
        jPanel_disciplineGuest.setBackground(new Color(163, 67, 26));
        jPanel_disciplinesLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_disciplineGuestMouseEntered

    private void jPanel_disciplineGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_disciplineGuestMouseExited
        jPanel_disciplineGuest.setBackground(new Color(52, 50, 46));
        jPanel_disciplinesLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_disciplineGuestMouseExited

    private void jPanel_resultGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_resultGuestMouseEntered
        jPanel_resultGuest.setBackground(new Color(163, 67, 26));
        jPanel_resultsLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_resultGuestMouseEntered

    private void jPanel_resultGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_resultGuestMouseExited
        jPanel_resultGuest.setBackground(new Color(52, 50, 46));
        jPanel_resultsLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_resultGuestMouseExited

    private void jPanel_scheduleGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_scheduleGuestMouseEntered
        jPanel_scheduleGuest.setBackground(new Color(163, 67, 26));
        jPanel_scheduleLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_scheduleGuestMouseEntered

    private void jPanel_scheduleGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_scheduleGuestMouseExited
        jPanel_scheduleGuest.setBackground(new Color(52, 50, 46));
        jPanel_scheduleLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_scheduleGuestMouseExited

    private void jPanel_teamGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_teamGuestMouseEntered
        jPanel_teamGuest.setBackground(new Color(163, 67, 26));
        jPanel_teamsLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_teamGuestMouseEntered

    private void jPanel_teamGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_teamGuestMouseExited
        jPanel_teamGuest.setBackground(new Color(52, 50, 46));
        jPanel_teamsLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_teamGuestMouseExited

    private void jPanel_registrationGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_registrationGuestMouseEntered
        jPanel_registrationGuest.setBackground(new Color(163, 67, 26));
        jPanel_registrationLeftGuest.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_jPanel_registrationGuestMouseEntered

    private void jPanel_registrationGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_registrationGuestMouseExited
        jPanel_registrationGuest.setBackground(new Color(52, 50, 46));
        jPanel_registrationLeftGuest.setBackground(new Color(52, 50, 46));
    }//GEN-LAST:event_jPanel_registrationGuestMouseExited

    
    // Timer methods
    public void SetImageSize(int i)
    {
        ImageIcon icon = new ImageIcon(imageList[i]);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(jLabel_imageGuest.getWidth(), jLabel_imageGuest.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(newImg);
        jLabel_imageGuest.setIcon(newImc);
    }
    
    public void timerSld()
    {
        tm = new Timer(5000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                SetImageSize(x);
                x += 1;
                if(x >= imageList.length)
                {
                    x = 0;
                }
            }
        });
        tm.start();
    }
    
 
    // Variables
    int xMouse;
    int yMouse;
    Timer tm;
    int x = 0;
    String[] imageList = {
        "src/View/Slider/4x100m_relay_women.png",
        "src/View/Slider/tripleJump_women.png",
        "src/View/Slider/RenaudLavillenie.png",
        "src/View/Slider/100mHurdles_women.png",
        "src/View/Slider/10000_women.png",
        "src/View/Slider/javelinThrow_men.png",
        "src/View/Slider/1500_women.png",
        "src/View/Slider/3000_steeplechase_women.png",
        "src/View/Slider/400mHurdles_women.png",
        "src/View/Slider/Obiri.png",
        "src/View/Slider/110mHurdles_men.png",
        "src/View/Slider/800m_women.png",
        "src/View/Slider/5000m_men.png",
        "src/View/Slider/4x400m_relay_men.png",
        "src/View/Slider/decathlon_eaton.png",
        "src/View/Slider/400m_men.png",
        "src/View/Slider/halfMarathon_men.png",
        "src/View/Slider/hammerThrow_women.png",
        "src/View/Slider/highJump_men.png",
        "src/View/Slider/javelinThrow_diamondLeague.png",
        "src/View/Slider/800m_men.png",
        "src/View/Slider/3000_steeplechase_men.png",
        "src/View/Slider/longJump_women.png",
        "src/View/Slider/EmmaCoburn.jpg",
        "src/View/Slider/marathon_women.png",
        "src/View/Slider/poleVault_women.png",
        "src/View/Slider/100m_women.png",
        "src/View/Slider/shotPut_men.png",
        "src/View/Slider/tripleJump_men.png",
        "src/View/Slider/OmarMcLeod.jpg"
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_athleteIconGuest;
    private javax.swing.JLabel jLabel_coachIconGuest;
    private javax.swing.JLabel jLabel_competitionIconGuest;
    private javax.swing.JLabel jLabel_disciplineIconGuest;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_imageGuest;
    public javax.swing.JLabel jLabel_leftMenuAthGuest;
    public javax.swing.JLabel jLabel_leftMenuCoachGuest;
    public javax.swing.JLabel jLabel_leftMenuCompGuest;
    public javax.swing.JLabel jLabel_leftMenuDisGuest;
    public javax.swing.JLabel jLabel_leftMenuRegGuest;
    public javax.swing.JLabel jLabel_leftMenuRsGuest;
    public javax.swing.JLabel jLabel_leftMenuSchGuest;
    public javax.swing.JLabel jLabel_leftMenuTmGuest;
    private javax.swing.JLabel jLabel_logOutGuest;
    private javax.swing.JLabel jLabel_logOutIconGuest;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_registrationIconGuest;
    private javax.swing.JLabel jLabel_resultIconGuest;
    private javax.swing.JLabel jLabel_rightArrowGuest;
    private javax.swing.JLabel jLabel_rightPanelResultsGuest;
    private javax.swing.JLabel jLabel_rightPanelScheduleGuest;
    private javax.swing.JLabel jLabel_scheduleIconGuest;
    private javax.swing.JLabel jLabel_teamIconGuest;
    private javax.swing.JLabel jLabel_titleDownGuest;
    private javax.swing.JLabel jLabel_titleUpGuest;
    private javax.swing.JLabel jLabel_trackAndFieldIconGuest;
    private javax.swing.JLabel jLabel_userIconGuest;
    private javax.swing.JLabel jLabel_usernameGuest;
    private javax.swing.JPanel jPanel_athleteGuest;
    private javax.swing.JPanel jPanel_athletesLeftGuest;
    private javax.swing.JPanel jPanel_coachGuest;
    private javax.swing.JPanel jPanel_coachesLeftGuest;
    private javax.swing.JPanel jPanel_competitionGuest;
    private javax.swing.JPanel jPanel_competitionsLeftGuest;
    private javax.swing.JPanel jPanel_disciplineGuest;
    private javax.swing.JPanel jPanel_disciplinesLeftGuest;
    private javax.swing.JPanel jPanel_headerGuest;
    private javax.swing.JPanel jPanel_imageSliderGuest;
    private javax.swing.JPanel jPanel_leftMenuGuest;
    private javax.swing.JPanel jPanel_mainPageGuest;
    private javax.swing.JPanel jPanel_registrationGuest;
    private javax.swing.JPanel jPanel_registrationLeftGuest;
    private javax.swing.JPanel jPanel_resultGuest;
    private javax.swing.JPanel jPanel_resultRightGuest;
    private javax.swing.JPanel jPanel_resultsLeftGuest;
    private javax.swing.JPanel jPanel_scheduleGuest;
    private javax.swing.JPanel jPanel_scheduleLeftGuest;
    private javax.swing.JPanel jPanel_scheduleRightGuest;
    private javax.swing.JPanel jPanel_teamGuest;
    private javax.swing.JPanel jPanel_teamsLeftGuest;
    private javax.swing.JPanel jPanel_usernameLeftGuest;
    // End of variables declaration//GEN-END:variables
}
