/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author Eider
 */
public class newAccount extends javax.swing.JFrame {

    /**
     * Creates new form newAccount
     */
    public newAccount() {
        initComponents();
        setLocationRelativeTo(null);
        jButton_send.setBackground(Color.decode("#d25722"));
        jButton_reset.setBackground(Color.decode("#d25722"));
        jLabel_username.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_username = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel_fullName = new javax.swing.JLabel();
        jTextField_fullName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton_send = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jPanel_header = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 50, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(477, 733));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_username.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username.setText("USERNAME:");
        jPanel1.add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jTextField_username.setBackground(new java.awt.Color(52, 50, 46));
        jTextField_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(240, 240, 240));
        jTextField_username.setText("Enter your username");
        jTextField_username.setBorder(null);
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 300, 10));

        jLabel_password.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password.setText("PASSWORD:");
        jPanel1.add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jPasswordField_password.setBackground(new java.awt.Color(52, 50, 46));
        jPasswordField_password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPasswordField_password.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField_password.setText("strongPassword");
        jPasswordField_password.setBorder(null);
        jPasswordField_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusLost(evt);
            }
        });
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 300, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 300, 10));

        jLabel_email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email.setText("EMAIL ACCOUNT:");
        jPanel1.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jTextField_email.setBackground(new java.awt.Color(52, 50, 46));
        jTextField_email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_email.setForeground(new java.awt.Color(240, 240, 240));
        jTextField_email.setText("Enter your email account");
        jTextField_email.setBorder(null);
        jTextField_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 300, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 300, 10));

        jLabel_fullName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel_fullName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fullName.setText("FULL NAME:");
        jPanel1.add(jLabel_fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 20));

        jTextField_fullName.setBackground(new java.awt.Color(52, 50, 46));
        jTextField_fullName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField_fullName.setForeground(new java.awt.Color(240, 240, 240));
        jTextField_fullName.setText("Enter your full name");
        jTextField_fullName.setBorder(null);
        jTextField_fullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_fullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_fullNameFocusLost(evt);
            }
        });
        jPanel1.add(jTextField_fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 300, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 300, 10));

        jButton_send.setBackground(new java.awt.Color(210, 87, 34));
        jButton_send.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_send.setForeground(new java.awt.Color(255, 255, 255));
        jButton_send.setText("SEND");
        jButton_send.setBorder(null);
        jButton_send.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 120, 50));

        jButton_reset.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton_reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_reset.setText("RESET");
        jButton_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 120, 50));

        jPanel_header.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_exit4.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 60));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_minimize_1.png"))); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 50, 60));

        jLabel_back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_backarrow3.png"))); // NOI18N
        jLabel_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_header.add(jLabel_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        jPanel1.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        if(jTextField_username.getText().equals(""))
        {
            jTextField_username.setText("Enter your username");
        }
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jPasswordField_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusLost
        if(jPasswordField_password.getText().equals(""))
        {
            jPasswordField_password.setText("strongPassword");
        }
    }//GEN-LAST:event_jPasswordField_passwordFocusLost

    private void jTextField_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusLost
        if(jTextField_email.getText().equals(""))
        {
            jTextField_email.setText("Enter your email account");
        }
    }//GEN-LAST:event_jTextField_emailFocusLost

    private void jTextField_fullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fullNameFocusLost
        if(jTextField_fullName.getText().equals(""))
        {
            jTextField_fullName.setText("Enter your full name");
        }
    }//GEN-LAST:event_jTextField_fullNameFocusLost

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        if(jTextField_username.getText().equals("Enter your username"))
        {
            jTextField_username.setText("");
            jTextField_username.setCaretColor(Color.decode("#f2f2f2"));
        }
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jPasswordField_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusGained
        if(jPasswordField_password.getText().equals("strongPassword"))
        {
            jPasswordField_password.setText("");
            jPasswordField_password.setCaretColor(Color.decode("#f2f2f2"));
        }
    }//GEN-LAST:event_jPasswordField_passwordFocusGained

    private void jTextField_fullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fullNameFocusGained
        if(jTextField_fullName.getText().equals("Enter your full name"))
        {
            jTextField_fullName.setText("");
            jTextField_fullName.setCaretColor(Color.decode("#f2f2f2"));
        }
    }//GEN-LAST:event_jTextField_fullNameFocusGained

    private void jTextField_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusGained
        if(jTextField_email.getText().equals("Enter your email account"))
        {
            jTextField_email.setText("");
            jTextField_email.setCaretColor(Color.decode("#f2f2f2"));
        }
    }//GEN-LAST:event_jTextField_emailFocusGained

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    int xMouse;
    int yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_reset;
    public javax.swing.JButton jButton_send;
    public javax.swing.JLabel jLabel_back;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_fullName;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_header;
    public javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField jTextField_email;
    public javax.swing.JTextField jTextField_fullName;
    public javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
