/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Eider
 */

public class showOneCh extends javax.swing.JFrame {

    /**
     * Creates new form addCompetition
     */
    public showOneCh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_idCh = new javax.swing.JLabel();
        jLabel_addressCh = new javax.swing.JLabel();
        jLabel_homeTownCh = new javax.swing.JLabel();
        jLabel_nationalityCh = new javax.swing.JLabel();
        jPanel_header = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_viewTitle = new javax.swing.JLabel();
        jLabel_teamCh = new javax.swing.JLabel();
        jLabel_phoneNumCh = new javax.swing.JLabel();
        jLabel_emailCh = new javax.swing.JLabel();
        jLabel_birthDateCh = new javax.swing.JLabel();
        jLabel_nameSurname = new javax.swing.JLabel();
        jLabel_countryCh = new javax.swing.JLabel();
        jLabel_idTitle = new javax.swing.JLabel();
        jLabel_countryTitle = new javax.swing.JLabel();
        jLabel_homeTownTitle = new javax.swing.JLabel();
        jLabel_addressTitle = new javax.swing.JLabel();
        jLabel_nationalityTitle = new javax.swing.JLabel();
        jLabel_birthDateTitle = new javax.swing.JLabel();
        jLabel_emailTitle = new javax.swing.JLabel();
        jLabel_phoneNumTitle = new javax.swing.JLabel();
        jLabel_teamTitle = new javax.swing.JLabel();
        jLabel_startYearTitle = new javax.swing.JLabel();
        jLabel_startYearCh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 50, 46)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_idCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_idCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_idCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 200, 40));

        jLabel_addressCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_addressCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_addressCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 200, 40));

        jLabel_homeTownCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_homeTownCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_homeTownCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 200, 40));

        jLabel_nationalityCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_nationalityCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_nationalityCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 200, 40));

        jPanel_header.setBackground(new java.awt.Color(52, 50, 46));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_headerMousePressed(evt);
            }
        });
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_exit4.png"))); // NOI18N
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 50, 50));

        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/30x30_minimize_1.png"))); // NOI18N
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel_header.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 50, 50));

        jLabel_viewTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_viewTitle.setForeground(new java.awt.Color(210, 87, 34));
        jLabel_viewTitle.setText("COACH PROFILE");
        jPanel_header.add(jLabel_viewTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 280, 30));

        jPanel1.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        jLabel_teamCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_teamCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_teamCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 200, 40));

        jLabel_phoneNumCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_phoneNumCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_phoneNumCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 200, 40));

        jLabel_emailCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_emailCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_emailCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 200, 40));

        jLabel_birthDateCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_birthDateCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_birthDateCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 200, 40));

        jLabel_nameSurname.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_nameSurname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel_nameSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 420, 50));

        jLabel_countryCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_countryCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_countryCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 200, 40));

        jLabel_idTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_idTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_idTitle.setText("ID:");
        jPanel1.add(jLabel_idTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 40));

        jLabel_countryTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_countryTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_countryTitle.setText("Country:");
        jPanel1.add(jLabel_countryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 40));

        jLabel_homeTownTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_homeTownTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_homeTownTitle.setText("Home Town:");
        jPanel1.add(jLabel_homeTownTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 40));

        jLabel_addressTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_addressTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_addressTitle.setText("Address:");
        jPanel1.add(jLabel_addressTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 289, -1, 40));

        jLabel_nationalityTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_nationalityTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_nationalityTitle.setText("Nationality:");
        jPanel1.add(jLabel_nationalityTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 329, -1, 40));

        jLabel_birthDateTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_birthDateTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_birthDateTitle.setText("Birth Date:");
        jPanel1.add(jLabel_birthDateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 369, -1, 40));

        jLabel_emailTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_emailTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_emailTitle.setText("Email Address:");
        jPanel1.add(jLabel_emailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 409, -1, 40));

        jLabel_phoneNumTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_phoneNumTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_phoneNumTitle.setText("Phone Number:");
        jPanel1.add(jLabel_phoneNumTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, 40));

        jLabel_teamTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_teamTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_teamTitle.setText("Team:");
        jPanel1.add(jLabel_teamTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, 40));

        jLabel_startYearTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_startYearTitle.setForeground(new java.awt.Color(52, 50, 46));
        jLabel_startYearTitle.setText("Start Year:");
        jPanel1.add(jLabel_startYearTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 489, -1, 40));

        jLabel_startYearCh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_startYearCh.setForeground(new java.awt.Color(52, 50, 46));
        jPanel1.add(jLabel_startYearCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMousePressed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    int xMouse;
    int yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel_addressCh;
    private javax.swing.JLabel jLabel_addressTitle;
    public javax.swing.JLabel jLabel_birthDateCh;
    private javax.swing.JLabel jLabel_birthDateTitle;
    public javax.swing.JLabel jLabel_countryCh;
    private javax.swing.JLabel jLabel_countryTitle;
    public javax.swing.JLabel jLabel_emailCh;
    private javax.swing.JLabel jLabel_emailTitle;
    private javax.swing.JLabel jLabel_exit;
    public javax.swing.JLabel jLabel_homeTownCh;
    private javax.swing.JLabel jLabel_homeTownTitle;
    public javax.swing.JLabel jLabel_idCh;
    private javax.swing.JLabel jLabel_idTitle;
    private javax.swing.JLabel jLabel_minimize;
    public javax.swing.JLabel jLabel_nameSurname;
    public javax.swing.JLabel jLabel_nationalityCh;
    private javax.swing.JLabel jLabel_nationalityTitle;
    public javax.swing.JLabel jLabel_phoneNumCh;
    private javax.swing.JLabel jLabel_phoneNumTitle;
    public javax.swing.JLabel jLabel_startYearCh;
    private javax.swing.JLabel jLabel_startYearTitle;
    public javax.swing.JLabel jLabel_teamCh;
    private javax.swing.JLabel jLabel_teamTitle;
    private javax.swing.JLabel jLabel_viewTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_header;
    // End of variables declaration//GEN-END:variables
}
